### ISSUE TITLE
Add a BoltDB implementation.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/projectionkit#12]
I expect this would be quite similar to the SQL adaptor, insofar as its role would be to setup the transaction and keep track of the OCC data before handing the transaction off to user code to update the DB.

**Comment by danilvpetrov** [comment]
Is there any intent to use BoltDB libraries such as [`asdine/storm`](https://github.com/asdine/storm) for the implementation of this issue's code?

**Comment by jmalloc** [comment]
In short, It's fine if it's really useful, but I'd prefer not to.

projectionkit itself would only need to do very minimal manipulation of buckets to keep track of the resource versions.

Either way, the user would still be free to use storm in their implementation as they see fit.

**Comment by danilvpetrov** [comment]
Fair enough.

**Comment by danilvpetrov** [comment]
Fixed with #13.
