### ISSUE TITLE
Tests hang if local Docker stack is not deployed.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/projectionkit#141]
I *think* this is started happening when `dynamodbprojection` was added, but not certain.

/cc @danilvpetrov

**Comment by danilvpetrov** [comment]
Confirmed test hanging on my end when Docker is not running. One of the solutions (confirmed as successful) is to introduce the following option to `github.com/aws/aws-sdk-go-v2/config.LoadDefaultConfig()` function in all `dynamoprojection` tests:

```go
...
			config.WithRetryer(
				func() aws.Retryer {
					return aws.NopRetryer{}
				},
			),
...

```

**Comment by jmalloc** [comment]
Ahh OK, so it just retries forever by default?

Is there a timeout on the test's `ctx`?

**Comment by danilvpetrov** [comment]
There is a 5-second timeout in all tests, but that seems ineffective. I *think* AWS DynamoDB client retries with a definite attempts, but when I only ran all `dynaomoprojection` tests with no Docker running it took more than a minute for all of them to fail.

That's the command I used to run only `dynamoprojection` tests: `go test -v -count 1 github.com/dogmatiq/projectionkit/dynamoprojection`
