### ISSUE TITLE
Rename sub-packages so that they don't conflict with other common package names.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/projectionkit#17]
- `sql` -> `sqlprojection`
- `boltdb` -> `boltprojection`

Thoughts?

**Comment by jmalloc** [comment]
`boltdb` does not conflict anyway, because the `bbolt` repo is actually a package named `bolt`.

**Comment by jmalloc** [comment]
/cc @koden-km as discussed.

Whatever we chose I wan't something short and consistent across the different DB types. I am not keen on using `pksql` like we do in aliases as the actual package name.

**Comment by koden-km** [comment]
Some suggestions `sqlkit`, `sqldb`, `dogmasql`, `sqlhandler`, `sqlh`, `sqlmessagehandler`, `sqlmh`.

**Comment by jmalloc** [comment]
You don't like `sqlprojection`? `sqlprojection.NoCompactBehavior` reads pretty nicely, for example. 

I know we don't always do a good job of following these guidelines, but have a quick read of this, too: https://blog.golang.org/package-names

**Comment by koden-km** [comment]
Ah yeah it seemed ok. I thought you didn't like it because it wasn't "short"?

**Comment by jmalloc** [comment]
Yeah, that's true.. shorter would be nicer, but I guess `sqlprojection` does feel ok because you use it to build an "sql projection", same words, same order.

**Comment by jmalloc** [comment]
I've just been looking at how we actually use these packages, and there's a few things going on that might be worth analysing before making a call on this:

- We import projectionkit's `sql` package in order to call `sql.New()`, typically inside application `Configure()` methods
- We tend to specify the projectionkit SQL driver to use explicitly because the auto-detection does not work when the underlying Go SQL driver is wrapped in middleware (such as for tracing/logging)
- When the names aren't aliases, the usage of `sql.New()` doesn't read correctly.. we're not making a "new SQL"

To illustrate, this is what typical projection configuration looks like now:

```go
import (
	pksql "github.com/dogmatiq/projectionkit/sql"
	pkmysql "github.com/dogmatiq/projectionkit/sql/mysql"
)

func (a *App) Configure(c dogma.ApplicationConfigurer) {
	c.RegisterProjection(
		pksql.MustNew(
			a.ReadDB,
			&a.SomeProjection,
			&pkmysql.Driver{},
		),
	)
}
```

Instead, we could use projectionkit's `mysql` package directly with an API like:

```go
import (
    "github.com/dogmatiq/projectionkit/sql/mysql"
)

func (a *App) Configure(c dogma.ApplicationConfigurer) {
	c.RegisterProjection(
		mysql.BindProjectionToDB(
			a.ReadDB,
			&a.CustomerAPIProjection,
		),
	)
}
```

Note that we could then import projectionkit's `mysql` package without an alias. This is unlikely to conflict as you don't typically import Go's SQL driver package for use. Instead, for better or worse, it's "underscope imported" in `main.go` so it can register itself with Go's SQL driver registry. In fact, the drivers for postgres are called `pq` and `pgx` and so would not conflict even if they were imported.

**Comment by jmalloc** [comment]
As of #79 the subpackages like `mysql` are gone entirely, so I think I can call this done.

The end result is that the packages have been renamed as per my original comment:

- `sql` -> `sqlprojection`
- `boltdb` -> `boltprojection`

And these packages have been removed entirely:

- `sql/mysql`
- `sql/postgres`
- `sql/sqlite`

I will follow this up with some changes that make the automatic driver detection work even when we're wrapping SQL drivers to add additional functionally (which we do to add tracing & metrics, etc).

After all this is done, usage will look like:

```go
import (
    "github.com/dogmatiq/projectionkit/sql/mysql"
)

func (a *App) Configure(c dogma.ApplicationConfigurer) {
	c.RegisterProjection(
		sqlprojection.New(
			a.ReadDB, // this may be nil
			&a.CustomerAPIProjection,
		),
	)
}
```
